const NAME_OR_PASSWORD_IS_REQUIRE = 'NAME_OR_PASSWORD_IS_REQUIRE';
const USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS';
const USER_DOES_NOT_EXISTS = 'USER_DOES_NOT_EXISTS';
const PASSWORD_IS_INCORRENT = 'PASSWORD_IS_INCORRENT';

module.exports = {
    NAME_OR_PASSWORD_IS_REQUIRE,
    USER_ALREADY_EXISTS,
    USER_DOES_NOT_EXISTS,
    PASSWORD_IS_INCORRENT
}